/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#2a6900',
        'primary-dim': '#235b00',
        'primary-container': '#84fb42',
        'primary-fixed': '#84fb42',
        'primary-fixed-dim': '#76ec33',
        'on-primary': '#d5ffb9',
        'on-primary-container': '#245c00',
        'on-primary-fixed': '#1a4700',
        'secondary': '#725800',
        'secondary-dim': '#644c00',
        'secondary-container': '#ffcb2a',
        'secondary-fixed': '#ffcb2a',
        'secondary-fixed-dim': '#f1bd00',
        'on-secondary': '#fff1d7',
        'on-secondary-container': '#5a4400',
        'on-secondary-fixed': '#423200',
        'tertiary': '#00628c',
        'tertiary-dim': '#00557a',
        'tertiary-container': '#3ebbff',
        'tertiary-fixed': '#3ebbff',
        'tertiary-fixed-dim': '#13adf3',
        'on-tertiary': '#e9f4ff',
        'on-tertiary-container': '#00344d',
        'on-tertiary-fixed': '#001a29',
        'error': '#b02500',
        'error-dim': '#b92902',
        'error-container': '#f95630',
        'on-error': '#ffefec',
        'on-error-container': '#520c00',
        'surface': '#f8f6f5',
        'surface-dim': '#d5d4d4',
        'surface-bright': '#f8f6f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f0f0',
        'surface-container': '#e9e8e7',
        'surface-container-high': '#e4e2e2',
        'surface-container-highest': '#dedcdc',
        'surface-variant': '#dedcdc',
        'surface-tint': '#2a6900',
        'on-surface': '#2e2f2f',
        'on-surface-variant': '#5c5b5b',
        'on-background': '#2e2f2f',
        'background': '#f8f6f5',
        'outline': '#777776',
        'outline-variant': '#aeadac',
        'inverse-surface': '#0e0e0e',
        'inverse-on-surface': '#9e9d9c',
        'inverse-primary': '#84fb42',
        'kahoot-red': '#e21b3c',
        'kahoot-blue': '#1368ce',
        'kahoot-yellow': '#d89e00',
        'kahoot-green': '#26890c',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
        label: ['Be Vietnam Pro', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
      keyframes: {
        shrink: {
          from: { width: '100%' },
          to: { width: '0%' },
        },
        'pulse-correct': {
          '0%': { transform: 'scale(1)' },
          '100%': { transform: 'scale(1.05)' },
        },
        'shake-error': {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-8px)' },
          '50%': { transform: 'translateX(8px)' },
          '75%': { transform: 'translateX(-8px)' },
        },
      },
      animation: {
        shrink: 'shrink 15s linear forwards',
        'pulse-correct': 'pulse-correct 0.5s ease-in-out infinite alternate',
        'shake-error': 'shake-error 0.4s ease-in-out',
      },
    },
  },
  plugins: [],
};
